# Generated by Django 4.1.6 on 2023-03-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default=models.FileField(upload_to='files'), max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=project.models.upload_to)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('size', models.PositiveIntegerField(blank=True, null=True)),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('workspace', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10000)),
                ('dashboards', models.CharField(blank=True, max_length=10000, null=True)),
                ('charts', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateField()),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.filemodel')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('charts', models.CharField(blank=True, max_length=5000, null=True)),
                ('text', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('x_axis', models.CharField(default=None, max_length=1000)),
                ('y_axis', models.CharField(default=None, max_length=1000)),
                ('chart_type', models.CharField(choices=[('area', 'Area Chart'), ('bar', 'Bar chart'), ('bubble', 'Bubble chart'), ('doughnut', 'Doughnut chart'), ('pie', 'Pie chart'), ('line', 'Line chart'), ('mixed', 'Mixed Chart'), ('polar area', 'Polar Area chart'), ('radar', 'Radar chart'), ('scatter', 'Scatter chart')], default=None, max_length=100)),
                ('options', models.CharField(default=None, max_length=1000)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('dashboard_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dashboard')),
                ('workspace_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.workspace')),
            ],
        ),
    ]
