# Generated by Django 4.1.6 on 2023-02-17 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=13, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('workspace', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(max_length=10000)),
                ('dashboards', models.CharField(blank=True, max_length=10000, null=True)),
                ('charts', models.CharField(blank=True, max_length=10000, null=True)),
                ('preview_image', models.ImageField(upload_to='')),
                ('created_on', models.DateField()),
                ('last_edit', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('database', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.database')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('dashboard', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('charts', models.TextField(blank=True, max_length=5000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('text', models.TextField(blank=True, max_length=10000, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('workspace_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('chart_id', models.UUIDField(default=uuid.uuid3, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('x_axis', models.CharField(default=None, max_length=1000)),
                ('y_axis', models.CharField(default=None, max_length=1000)),
                ('chart_type', models.CharField(choices=[('area chart', 'Area Chart'), ('bar chart', 'Bar chart'), ('bubble chart', 'Bubble chart'), ('doughnut chart', 'Doughnut chart'), ('pie chart', 'Pie chart'), ('line chart', 'Line chart'), ('mixed chart', 'Mixed Chart'), ('polar area chart', 'Polar Area chart'), ('radar chart', 'Radar chart'), ('scatter chart', 'Scatter chart')], default=None, max_length=100)),
                ('options', models.CharField(default=None, max_length=1000)),
                ('summary', models.CharField(blank=True, max_length=1000, null=True)),
                ('dashboard_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.dashboard')),
                ('workspace_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.workspace')),
            ],
        ),
    ]
