# Generated by Django 4.1.6 on 2023-02-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_chart_chart_id_alter_dashboard_dashboard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='created_on',
            field=models.DateField(auto_now_add=True),
        ),
    ]
