# Generated by Django 4.1.6 on 2023-02-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_dashboard_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='charts',
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='text',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='name',
            field=models.CharField(max_length=10000),
        ),
    ]
