# Generated by Django 4.1.6 on 2023-02-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_database_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
        migrations.AlterField(
            model_name='chart',
            name='chart_type',
            field=models.CharField(choices=[('area', 'Area Chart'), ('bar', 'Bar chart'), ('bubble', 'Bubble chart'), ('doughnut', 'Doughnut chart'), ('pie', 'Pie chart'), ('line', 'Line chart'), ('mixed', 'Mixed Chart'), ('polar area', 'Polar Area chart'), ('radar', 'Radar chart'), ('scatter', 'Scatter chart')], default=None, max_length=100),
        ),
    ]
