# Generated by Django 4.1.6 on 2023-03-21 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_filemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='image',
        ),
        migrations.RemoveField(
            model_name='workspace',
            name='preview_image',
        ),
    ]
