# Generated by Django 4.1.6 on 2023-03-21 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_remove_dashboard_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='database',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.filemodel'),
        ),
    ]
